### ISSUE TITLE
Create a new tag with LICENSE file

### ISSUE THREAD

**Issue by dschniepp** [JakubOnderka/PHP-Console-Color#12]
Thank you very much for the effort you put in this package. I would be awesome if you could release a new version of the packages which includes the later added LICENSE file. We use a tool to autogenerate one big license file which stashes all licenses of our dependencies and would be really happy to have the `PHP-Console-Color` LICENSE automatically added.

**Comment by JakubOnderka** [comment]
Sorry for delay, but `LICENSE` file is included in v0.2 release.
